alter table WHEREISMYMONEYLEBOVSKIY_LETTER_BASE alter column DEBITOR_ID rename to DEBITOR_ID__U19117 ^
alter table WHEREISMYMONEYLEBOVSKIY_LETTER_BASE alter column DEBITOR_ID__U19117 set null ;
alter table WHEREISMYMONEYLEBOVSKIY_LETTER_BASE drop constraint FK_WHEREISMYMONEYLEBOVSKIY_LETTER_BASE_ON_DEBITOR ;
drop index IDX_WHEREISMYMONEYLEBOVSKIY_LETTER_BASE_ON_DEBITOR ;
-- alter table WHEREISMYMONEYLEBOVSKIY_LETTER_BASE add column DEBTOR_ID varchar(36) ^
-- update WHEREISMYMONEYLEBOVSKIY_LETTER_BASE set DEBTOR_ID = <default_value> ;
-- alter table WHEREISMYMONEYLEBOVSKIY_LETTER_BASE alter column DEBTOR_ID set not null ;
alter table WHEREISMYMONEYLEBOVSKIY_LETTER_BASE add column DEBTOR_ID varchar(36) not null ;
